
<table id="agenda-table" class="table table-striped ">
                            <thead>
                            <tr>
                                <th></th>
                                <th width="40%">SALA BARRIA</th>
                                <th width="40%">SALA A3</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td class="time">9:00-9:20</td>
                                <td>Presentación</td>
                                <td>Presentación</td>
                            </tr>
                            <tr>
                                <td class="time">9:30-10:20</td>
                                <td>
                                    <a href="/speaker/angelica-lozano/#talk-details">
                                        <h5><?php echo $talk_helper('angelica-lozano', 'title') ?></h5>
                                        <p><?php echo $talk_helper('angelica-lozano', 'name') ?></p>
                                    </a>
                                </td>
                                <td>
                                    <a href="/speaker/carmen-ansio/#talk-details">
                                        <h5><?php echo $talk_helper('carmen-ansio', 'title') ?></h5>
                                        <p><?php echo $talk_helper('carmen-ansio', 'name') ?></p>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td class="time">10:30-11:20</td>
                                <td>
                                    <a href="/speaker/franziska-sauerwein/#talk-details">
                                        <h5><?php echo $talk_helper('franziska-sauerwein', 'title') ?></h5>
                                        <p><?php echo $talk_helper('franziska-sauerwein', 'name') ?></p>
                                    </a>
                                </td>
                                <td>
                                    <a href="/speaker/diana-aceves/#talk-details">
                                        <h5><?php echo $talk_helper('diana-aceves', 'title') ?></h5>
                                        <p><?php echo $talk_helper('diana-aceves', 'name') ?></p>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td class="time">11:30-12:00</td>
                                <td colspan="2">Networking + café</td>
                            </tr>
                            <tr>
                                <td class="time">12:00-12:50</td>
                                <td>
                                    <a href="/speaker/mario-marin/#talk-details">
                                        <h5><?php echo $talk_helper('mario-marin', 'title') ?></h5>
                                        <p><?php echo $talk_helper('mario-marin', 'name') ?></p>
                                    </a>
                                </td>
                                <td>
                                    <a href="/speaker/bea-martin/#talk-details">
                                        <h5><?php echo $talk_helper('bea-martin', 'title') ?></h5>
                                        <p><?php echo $talk_helper('bea-martin', 'name') ?></p>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td class="time">13:00-13:50</td>
                                <td>
                                    <a href="/speaker/javi-y-rafa/#talk-details">
                                        <h5><?php echo $talk_helper('javi-y-rafa', 'title') ?></h5>
                                        <p><?php echo $talk_helper('javi-y-rafa', 'name') ?></p>
                                    </a>
                                </td>
                                <td>
                                    <a href="/speaker/amalia-hernandez/#talk-details">
                                        <h5><?php echo $talk_helper('amalia-hernandez', 'title') ?></h5>
                                        <p><?php echo $talk_helper('amalia-hernandez', 'name') ?></p>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td class="time">>14:00</td>
                                <td colspan="2">Networking + pintxos y poteo</td>
                            </tr>
                            </tbody>
</table>