<table id="agenda-table" class="table table-striped ">
                            <thead>
                            <tr>
                                <th></th>
                                <th width="40%">SALA BARRIA</th>
                                <th width="40%">SALA A3</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td class="time">9:00-9:20</td>
                                <td>Presentación</td>
                                <td>Presentación</td>
                            </tr>
                            <tr>
                                <td class="time">9:30-10:20</td>
                                <td>
                                    <a href="/speaker/dani-latorre/#talk-details">
                                        <h5><?php echo $talk_helper('dani-latorre', 'title') ?></h5>
                                        <p><?php echo $talk_helper('dani-latorre', 'name') ?></p>
                                    </a>
                                </td>
                                <td>
                                    <a href="/speaker/belen-albeza/#talk-details">
                                        <h5><?php echo $talk_helper('belen-albeza', 'title') ?></h5>
                                        <p><?php echo $talk_helper('belen-albeza', 'name') ?></p>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td class="time">10:30-11:20</td>
                                <td>
                                    <a href="/speaker/ines-huertas/#talk-details">
                                        <h5><?php echo $talk_helper('ines-huertas', 'title') ?></h5>
                                        <p><?php echo $talk_helper('ines-huertas', 'name') ?></p>
                                    </a>
                                </td>
                                <td>
                                    <a href="/speaker/ricardo-borillo/#talk-details">
                                        <h5><?php echo $talk_helper('ricardo-borillo', 'title') ?></h5>
                                        <p><?php echo $talk_helper('ricardo-borillo', 'name') ?></p>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td class="time">11:30-12:00</td>
                                <td colspan="2">Networking + café</td>
                            </tr>
                            <tr>
                                <td class="time">12:00-12:50</td>
                                <td>
                                    <a href="/speaker/edu-ferro/#talk-details">
                                        <h5><?php echo $talk_helper('edu-ferro', 'title') ?></h5>
                                        <p><?php echo $talk_helper('edu-ferro', 'name') ?></p>
                                    </a>
                                </td>
                                <td>
                                    <a href="/speaker/virginia-aguirre/#talk-details">
                                        <h5><?php echo $talk_helper('virginia-aguirre', 'title') ?></h5>
                                        <p><?php echo $talk_helper('virginia-aguirre', 'name') ?></p>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td class="time">13:00-13:50</td>
                                <td>
                                    <a href="/speaker/cristina-santamarina/#talk-details">
                                        <h5><?php echo $talk_helper('cristina-santamarina', 'title') ?></h5>
                                        <p><?php echo $talk_helper('cristina-santamarina', 'name') ?></p>
                                    </a>
                                </td>
                                <td>
                                    <a href="/speaker/jose-armesto/#talk-details">
                                        <h5><?php echo $talk_helper('jose-armesto', 'title') ?></h5>
                                        <p><?php echo $talk_helper('jose-armesto', 'name') ?></p>
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td class="time">>14:00</td>
                                <td colspan="2">Networking + pintxos y poteo</td>
                            </tr>
                            </tbody>
</table>